// <auto-generated />
using System;
using CasaCambio.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CasaCambio.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326210446_AgregarLimiteDeudaYConfiguracion")]
    partial class AgregarLimiteDeudaYConfiguracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CasaCambio.Server.Models.Arqueo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaId")
                        .HasColumnType("integer")
                        .HasColumnName("cuenta_id");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("numeric")
                        .HasColumnName("diferencia");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int?>("MovimientoAjusteId")
                        .HasColumnType("integer")
                        .HasColumnName("movimiento_ajuste_id");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("SaldoArqueo")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_arqueo");

                    b.Property<decimal>("SaldoSistema")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_sistema");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("MovimientoAjusteId");

                    b.ToTable("arqueos");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accion");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidad");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_nombre");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("text")
                        .HasColumnName("valores_anteriores");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("text")
                        .HasColumnName("valores_nuevos");

                    b.HasKey("Id");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.CierreCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadCompras")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_compras");

                    b.Property<int>("CantidadVentas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_ventas");

                    b.Property<bool>("Cerrado")
                        .HasColumnType("boolean")
                        .HasColumnName("cerrado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("SaldoCajaARS")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_caja_ars");

                    b.Property<decimal>("SaldoCajaEUR")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_caja_eur");

                    b.Property<decimal>("SaldoCajaUSD")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_caja_usd");

                    b.Property<decimal>("TotalComprasARS")
                        .HasColumnType("numeric")
                        .HasColumnName("total_compras_ars");

                    b.Property<decimal>("TotalComprasUSD")
                        .HasColumnType("numeric")
                        .HasColumnName("total_compras_usd");

                    b.Property<decimal>("TotalDiferencias")
                        .HasColumnType("numeric")
                        .HasColumnName("total_diferencias");

                    b.Property<decimal>("TotalVentasARS")
                        .HasColumnType("numeric")
                        .HasColumnName("total_ventas_ars");

                    b.Property<decimal>("TotalVentasUSD")
                        .HasColumnType("numeric")
                        .HasColumnName("total_ventas_usd");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("cierres_caja");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.ConfiguracionSistema", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Clave");

                    b.ToTable("configuracion_sistema");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.CotizacionDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CotizacionCompra")
                        .HasColumnType("numeric")
                        .HasColumnName("cotizacion_compra");

                    b.Property<decimal>("CotizacionVenta")
                        .HasColumnType("numeric")
                        .HasColumnName("cotizacion_venta");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("MonedaId")
                        .HasColumnType("integer")
                        .HasColumnName("moneda_id");

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.ToTable("cotizaciones_diarias");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("LimiteDeuda")
                        .HasColumnType("numeric")
                        .HasColumnName("limite_deuda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("cuentas");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.EstadoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArqueoId")
                        .HasColumnType("integer")
                        .HasColumnName("arqueo_id");

                    b.Property<int>("CuentaId")
                        .HasColumnType("integer")
                        .HasColumnName("cuenta_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<decimal>("SaldoApertura")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_apertura");

                    b.Property<decimal?>("SaldoCierre")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_cierre");

                    b.Property<string>("UsuarioApertura")
                        .HasColumnType("text")
                        .HasColumnName("usuario_apertura");

                    b.Property<string>("UsuarioCierre")
                        .HasColumnType("text")
                        .HasColumnName("usuario_cierre");

                    b.HasKey("Id");

                    b.HasIndex("ArqueoId");

                    b.HasIndex("CuentaId");

                    b.ToTable("estados_caja");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("monedas");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaId")
                        .HasColumnType("integer")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<int>("OperacionId")
                        .HasColumnType("integer")
                        .HasColumnName("operacion_id");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("OperacionId");

                    b.ToTable("movimientos");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.Operacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<decimal>("CotizacionAplicada")
                        .HasColumnType("numeric")
                        .HasColumnName("cotizacion_aplicada");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("MontoTotalDestino")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total_destino");

                    b.Property<decimal>("MontoTotalOrigen")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total_origen");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_operacion");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("operaciones");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.SaldoCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaId")
                        .HasColumnType("integer")
                        .HasColumnName("cuenta_id");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId", "Moneda")
                        .IsUnique();

                    b.ToTable("saldos_cuenta");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.TenenciaMoneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("cantidad_total");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_total");

                    b.Property<int>("MonedaId")
                        .HasColumnType("integer")
                        .HasColumnName("moneda_id");

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.ToTable("tenencias_moneda");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<string>("TokenConfirmacion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_confirmacion");

                    b.Property<DateTime?>("TokenExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expiracion");

                    b.Property<string>("TokenRecuperacion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_recuperacion");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.Arqueo", b =>
                {
                    b.HasOne("CasaCambio.Server.Models.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasaCambio.Server.Models.Movimiento", "MovimientoAjuste")
                        .WithMany()
                        .HasForeignKey("MovimientoAjusteId");

                    b.Navigation("Cuenta");

                    b.Navigation("MovimientoAjuste");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.CotizacionDiaria", b =>
                {
                    b.HasOne("CasaCambio.Server.Models.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.EstadoCaja", b =>
                {
                    b.HasOne("CasaCambio.Server.Models.Arqueo", "Arqueo")
                        .WithMany()
                        .HasForeignKey("ArqueoId");

                    b.HasOne("CasaCambio.Server.Models.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arqueo");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.Movimiento", b =>
                {
                    b.HasOne("CasaCambio.Server.Models.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasaCambio.Server.Models.Operacion", "Operacion")
                        .WithMany("Movimientos")
                        .HasForeignKey("OperacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("Operacion");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.Operacion", b =>
                {
                    b.HasOne("CasaCambio.Server.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.SaldoCuenta", b =>
                {
                    b.HasOne("CasaCambio.Server.Models.Cuenta", "Cuenta")
                        .WithMany("Saldos")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.TenenciaMoneda", b =>
                {
                    b.HasOne("CasaCambio.Server.Models.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.Cuenta", b =>
                {
                    b.Navigation("Saldos");
                });

            modelBuilder.Entity("CasaCambio.Server.Models.Operacion", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
