// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaCambio.Models;

#nullable disable

namespace SistemaCambio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225201829_AgregarOperacionesYClientes")]
    partial class AgregarOperacionesYClientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaCambio.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("SistemaCambio.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moneda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("cuentas");
                });

            modelBuilder.Entity("SistemaCambio.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaId")
                        .HasColumnType("integer")
                        .HasColumnName("cuenta_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<int>("OperacionId")
                        .HasColumnType("integer")
                        .HasColumnName("operacion_id");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("OperacionId");

                    b.ToTable("movimientos");
                });

            modelBuilder.Entity("SistemaCambio.Models.Operacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<decimal>("CotizacionAplicada")
                        .HasColumnType("numeric")
                        .HasColumnName("cotizacion_aplicada");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("MontoTotalDestino")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total_destino");

                    b.Property<decimal>("MontoTotalOrigen")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total_origen");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_operacion");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("operaciones");
                });

            modelBuilder.Entity("SistemaCambio.Models.Movimiento", b =>
                {
                    b.HasOne("SistemaCambio.Models.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCambio.Models.Operacion", "Operacion")
                        .WithMany("Movimientos")
                        .HasForeignKey("OperacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("Operacion");
                });

            modelBuilder.Entity("SistemaCambio.Models.Operacion", b =>
                {
                    b.HasOne("SistemaCambio.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SistemaCambio.Models.Operacion", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
